#ifndef SANITIZER_PLATFORM_LIMITS_CHEERPWASM_H
#define SANITIZER_PLATFORM_LIMITS_CHEERPWASM_H

#if SANITIZER_CHEERPWASM

#include <stdio.h>

typedef FILE __sanitizer_FILE;
extern unsigned mbstate_t_sz;
#define SANITIZER_HAS_STRUCT_FILE 0

#endif // SANITIZER_CHEERPWASM

#endif // SANITIZER_PLATFORM_LIMITS_CHEERPWASM_H 
